freeipa/freeipa-pr-ci

.gitignore
README.md
ansible/create_template_box.yml
ansible/group_vars/all/vars.yml
ansible/roles/box_prepare/tasks/main.yml
ansible/roles/machine_build/tasks/clone_git_repo.yml
ansible/roles/machine_build/tasks/create_rpms.yml
ansible/roles/machine_build/tasks/create_sources.yml
ansible/roles/machine_build/tasks/create_spec.yml
ansible/roles/machine_build/tasks/generate_build_version.yml
ansible/roles/machine_build/tasks/main.yml
ansible/roles/machine_build_template/tasks/cleanup.yml
ansible/roles/machine_build_template/tasks/install_freeipa_builddeps.yml
ansible/roles/machine_build_template/tasks/install_packages.yml
ansible/roles/machine_build_template/tasks/main.yml
ansible/roles/machine_build_template/tasks/setup_mock.yml
ansible/roles/machine_template/tasks/install_packages.yml
create-template-box
rpms/README.md

Box template is now generated with mock environment with the
necessary build dependencies. An ansible playbook can be used
to build rpms from git sources.

box template: added mock environment for build

---

ansible/roles/machine/workarounds/tasks/gssproxy_nfsutils.yml
ansible/roles/machine/workarounds/tasks/main.yml

systemctl restart gssproxy would fail during ipa-server-install,
becase nfs-utils was installed, but nfs wasn't started.
Remove once https://bugzilla.redhat.com/show_bug.cgi?id=1452881
is fixed.

template: add workaround for gssproxy nfs-utils issue

---

github/prci_github/internals.py

For easier future changes all jobs are inside 'jobs' key.

github: Change tasks file format

---

ansible/prepare_devel_test_runners.yml

Add a check to avoid accidental deployment of development runners
against FreeIPA repo.

ansible: check monitored repo when deploying development runners

---

ansible/roles/machine/provision/tasks/main.yml

When freeipa requires a new package that is not in COPR, because it
is available in fedora/updates repo, this will turn on the extra
repositories.
Fixes #28

ansible provision: enable fedora repos if needed

---

ansible/create_template_box.yml
ansible/group_vars/all/vars.yml
ansible/roles/box/prepare/defaults/main.yml
ansible/roles/machine/cleanup/tasks/clean_hostname.yml

A more user-friendly way to switch between Fedora templates should be considered in the future. As of now, the appropriate sections of `create_template_box.yml` have to be (un)commented.

Allow creation of F26 template

---

templates/Vagrantfile.build
templates/Vagrantfile.run_pytest

Guest VMs aren't accessed from the outside network and bridged
mode caused network slowdowns combined with nested virtualization.
NAT mode is used by default, which enables both network access to internet
from VM and network access between the VMs themselves.

vagrant: remove bridged network

---

ansible/roles/runner/files/libvirt_default_pool.xml
ansible/roles/runner/tasks/create_libvirt_pool.yml
ansible/roles/runner/tasks/main.yml
tasks/constants.py
tasks/requirements.txt
tasks/tasks.py
tasks/vagrant.py

By default, libvirt copies the template image from vagrant to its local
storage pool. To save storage space on runners, this template image is
linked from the vagrant box directory to libvirt storage.
This option should be turned off for local execution, because it requires
correct permissions for the .vagrant.d directory.
Signed-off-by: Tomas Krizek <tomas.krizek@mailbox.org>

runner: link template image from vagrant to libvirt

---

github/prci_github/internals.py

Include number of tasks completed or in progress on the same PR. This change
should prioritize finishing testing of PR over starting testing of new PR.

github: Change task priority computation

---

github/prci.py
github/prci_github/internals.py
requirements.txt

When runner takes task and then craches the task would become stale and manual
re-run would be required. Since time when the task in included in task
description and timeout for the task is specified in task configuration we can
detect such situation and regenerate such task so other runner can take it.

github: Recovery from runner craches

---

README.md

In order to take advantage of hard links to conserve storage space,
libvirt and vagrant image directory have to be on the same partition.

README: add partitioning prerequisite

---

templates/beaker-min.xml

/root/.vagrant.d and /var/lib/libvirt have to be on the same
partition to take advantage of the hard links to conserve
storage space.

beaker: use one partition for root

---

github/prci_github/adapter.py

To avoid triggering GitHub's abuse policy, slow down API calls.
Using up to 1500 req/minute seems to work fine, so this should
allow scaling up to 25 runners.

github: rate-limit API calls

---

ansible/roles/machine/setup/tasks/install_packages.yml

This package is required for Python3 testing.

tempalte: add python3-paramiko

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/provision/templates/ipa-test-config.yaml

Instead of relying on our internal DNS infrastructure, use the DNS
server from vagrant, which forwards the requests to hosts' DNS server.

vm provisioning: use dns server provided by vagrant

---

ansible/roles/machine/setup/defaults/main.yml
ansible/roles/machine/setup/tasks/install_packages.yml

It's necessary to use paramiko v2.2.1 due to issues with gssapi (https://github.com/paramiko/paramiko/issues/1069)

Adding dependencies to run ipa-tests with python3

---

README.md

The required version is raised as blocks can be named since
ansible 2.3.0

Bump required ansible version

---

ansible/roles/runner/handlers/main.yml

Often the 2 minute timeout wasn't enough for the machine to come back
and the playbook would seemingly fail on the last step. Even though the
error was harmless, it could confuse users.

runner: don't wait for reboot after deployment

---

ansible/callback_plugins/human_log.py

Ansible 2.4.0 made some backward incompatible changes which prevented
human_log.py to work properly. This ensures it works with both <2.4 and
>= 2.4 Ansible version.
Issue in Ansible: https://github.com/ansible/ansible/issues/30597

ansible: make callback plugin forward compatible

---

ansible/roles/machine/provision/templates/ipa-test-config.yaml

To run the external CA tests, we have to provide the absolute path of the certs.

Fixing the ipa-test-config.yaml in order to run external CA tests

---

ansible/roles/machine/provision/tasks/main.yml

With this change, the installed packages will be listed in the
/vagrant/installed_packages.log.gz files. After sending the
stdout to the file, we have a task that collects the files
in the shared directory. This is done via the shared directory
inside the vagrant VMs in `/vagrant`.
For more info about it, check `tasks/remote_storage.py::GzipLogFiles`
Fixes #106

Adding installed packages list to a separate file

---

tasks/tasks.py

Since commit d39456a882efacbfefcc1f987ebf89ceeb761f61 in freeIPA, if freeIPA
is built using python3, ipa-run-tests will use python3 by default.
However, paramiko it's showing problems to collect logs from the hosts when using py3.
This is just a hotfix to have the logs back as soon as possible.

Force ipa-run-tests to use python 2

---

templates/Vagrantfile.run_pytest

We consider 0 as normal the beginning of the numbering.
Resolves #74

Fix replica numbering

---

ansible/create_template_box.yml

Generate F27 box based on official F27 vagrant-libvirt image.
Use https://github.com/abbra/freeipa/pull/6/commits/508f123b25fb25e3b69847a69ce0a5547731f469 against freeIPA to introduce F27 box there.

Migrate to F27 box

---

ansible/roles/runner/defaults/main.yml
ansible/roles/runner/tasks/setup.yml

It's possible to change the value of 300M in the `defaults/main.yml` file.
Fixes #53

Limiting the systemd journal size

---

ansible/roles/runner/handlers/main.yml
ansible/roles/runner/tasks/enable_nested_virt.yml
ansible/roles/runner/tasks/setup.yml

Nested virt config tested with both kvm_intel and kvm_amd

do not require reboot during runner deployment

---

github/prci.py
github/prci_github/__init__.py
github/prci_github/internals.py
tasks/constants.py
tasks/tasks.py
templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client

In order to have more tests running in upstream PR CI
infrastructure, we need to support multiple topologies:
multiple master, replicas and clients. This PR address this.
To know the resources that a given task should have to
run it, the freeipa/freeipa/.freeipa-pr-ci.yml file will
declare how much RAM and CPUs are needed. Using this syntax:
```
topologies:
master_1repl: &master_1repl
name: master_1repl
cpu: 2
memory: 4098
master_1repl_1client: &master_1repl_1client
name: master_1repl_1client
cpu: 6
memory: 6144
```
After declaring the topologies, the tasks will be able
to use it with this syntax:
```
fedora-26/simple_replication:
...
job:
class: RunPytest
args:
...
topology: *master_1repl
```
Is IMPORTANT to say that, the name of the topology
must match with the name of a Vagrantfile …

Enabling multiple topologies

---

ansible/prepare_devel_test_runners.yml

Prompt asks for PR CI repo owner/branch from which test runner will be deployed
not for PR CI repo which will be tested.

Change prompt during preparing devel runner

---

ansible/cleanup_runner_disk.yml

Make sure the playbook is idempotent and doesn't fail when the box was
already removed (and thus isn't present and can't be removed again).
Related #27

ansible: make disk_cleanup idempotent

---

README.md

When setting up a new runner user is prompted for inserting some data
about repositories and GitHub. This might be automated by adding
an argument -e to ansible and specify values as key=value pairs.
Those keys has been visible only in ansible playbooks and one has
to look for them. Now they are visible in documentation.

Extend documentation by adding keys which has been only in playbooks

---

ansible/roles/runner/files/prci.service

Configure prci.service to be restarted after 10 minutes if it fails.
Rate-limiting of startup is disabled, so systemd will attempt to restart
the service indefinitely as long as it fails.
Fixes: #141

prci.service: auto-restart service on failure

---

ansible/roles/machine/provision/tasks/main.yml
tasks/tasks.py
templates/run_pytest.vars.yml

Enable a package update during VM provisioning in RunPytest job.
Related #109

VM provisioning: add option to update packages

---

ansible/roles/runner/tasks/deploy_pr_ci.yml
ansible/roles/runner/tasks/setup.yml

Instead of using custom COPR repos, get the packages from pip, since we have the required version there.

Removing use of custom COPR repo

---

templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

As said here [1], a newer version of Vagrant is needed. Otherwise, the process to add a box will fail with a 404, because the "server/repo URL" has been moved.
* Installing new Vagrant version
Instead of relying on fedora packages, this changes the code to get the rpm directly from vagrantcloud source. I prefer to maintain a simple URL that can be easily changed when it's needed.
* Adding the necessary packages to the new version
As can be checked here: https://github.com/vagrant-libvirt/vagrant-libvirt
* This commit also specify the provider (libvirt in our case) to use in
vagrant up, as it's needed by the new vagrant version.
[1] https://groups.google.com/forum/#!msg/vagrant-up/H8C68UTkosU/qz4YUmAgBAAJ

Changing to install a newer Vagrant version

---

github/prci_github/adapter.py

As commit a811f1cc explains, we need to slow down the API calls to avoid
hitting the limit of requests per minute. To have more than ~20 runners, it's necessary to increase this time. Increasing it to 1.5s would allow us to have around 40 runners.
Important to say that the limit is hit even when runners are using the cached requests, as it's well explained in [1].
[1] https://github.com/freeipa/freeipa-pr-ci/tree/master/doc#abuse-limit

Increase the time between requests

---

ansible/roles/runner/tasks/deploy_pr_ci.yml

When trying to install CacheControl with pip 9.0.1 and setuptools
python3-setuptools-36.0.1-1, it fails with message:
AttributeError: 'NoneType' object has no attribute 'ensure_finalized'
Updating setuptools to latest version (setuptools-38.5.1)
fixes the problem.

Updating setuptools to fix problem when installing cachecontrol

---

whitelist.yml

We need this to have nightly PRs in freeipa repo

Adding freeipa-pr-ci user to whitelist

---

github/prci_github/internals.py

Now downloading tasks file is using an GitHub API call
(GET /repos/:owner/:repo/pulls/:number/files). It can be useful
in some cases but not in ours. In our case the `.freeipa-pr-ci.yaml`
file exists either in the head or base branches. So we can retrieve
it just by constructing the URL. So then if the tasks file doesn't
exist in the head, we will just download it from the base.

Do not use API call for downloading tasks file

---

github/prci_github/internals.py

Previous code was raising `KeyError: 'repo'` on `tasks_file_url.format(url)`. We should only pass url as a parameter to session.get.

Fix keyerror when trying to get tasks file

---

tasks/tasks.py

We can easily produce also junit.xml so that system which can automatically
process it can do it from published artifacs. This might be one of the ways
how to automatically process nightly or other testing results.

Export junit.xml in pytest to allow automatic processing

---

github/prci_github/adapter.py

With 1.5 seconds of delay, the runners could wait more than 1,5 hours to
get a new task (depending on the number of PRs). Switching it back to
0.5 to decrease this time even though this limit the number of maximum
runners.

Decreasing time between each request

---

tasks/remote_storage.py

Screenshot is a png - already compressed. GZIP compression doesn't save much
additional space.
Compressing screenshots creates UX issue: Firefox is not able to directly
open png.gz file. So one must download it, uncompress and then open which
takes time.
By not compressing screenshots, one can easily view Web UI test failure
directly from uploaded artifacts.

Artifacts: do not compress screenshots (png files)

---

ansible/roles/runner/templates/config.yml

Now logger format doesn't contain spaces after its level name,
module name and the message.
This patch adds spaces so log becomes a little easier to read.

Make logger format fancy

---

tasks/vagrant.py

Now the fallback after Vagrant destroy PopenException is completely
useless as it will not kill Vagrant and will not restart libvirtd
service.
This patch fixes it.
Also added pkill call to make sure there are no lost virtual machines.

tasks/vagrant.py VagrantCleanup fix

---

ansible/roles/runner/tasks/setup.yml

Now runner preparation does not configure firewalld service and
open ports for NFS related services. As the result Vagrant can't
mount NFS directory so no task will be run.
This patch eliminates this kind of thing.

Ensure firewalld is installed and configured

---

ansible/roles/runner/tasks/setup.yml

Now the runner's packages are not getting upgraded and this leads
to many problems, such as security issues or not working executables.
This patch adds dnf upgrade call during runner's setup.

Upgrade runner's packages during its setup

---

github/internals/entities.py

Now poll_status method of a World class throws the RuntimeError
which is not being catched so the whole PR CI instance dies.
This patch fixes it.

Fix poll_status to raise EnvironmentError

---

github/internals/entities.py

Now the already processed (succeeded and failed) task will be
locked if it was gathered and yielded by prci before it was
taken by any runner and changed status from pending.
This patch adds the check for this kind of thing to the lock
method of Task class and fixes the behaviour.

Task.lock: don't lock already processed task

---

github/internals/entities.py

After eddec9de2e0ec814e3bc49c5e2759fbc329e09e6 CI can't create
tasks for new PRs as set_unassigned method stopped to catch the
exception as the type of it was changed.
This patch fixes it.

Fix tasks creation on GitHub

---

github/prci.py

Now prci will try to set rerun pending for stalled task and this
update will fail as set_rerun has check if task is taken. In this
case the update of a stalled task will be performed over and over
again that will lead to triggering of abuse limit of GitHub API.
This patch makes the prci to set stalled task status to unassigned
and fixes this problem.

[scalability] Fix behaviour to update stalled task

---

github/prci.py

Now prci will try to lock a task to take even when its status does
not exist on GitHub.
This patch fixes this wrong behaviour.

Don't lock a task when its status doesn't exist

---

github/internals/entities.py

Fixes the nasty stupid bug which was introduced in
462607821a914413a12c2c86af21fb2f0fa8d0c2 and leads to not updating
the status to rerun pending when task is stuck.
This patch fixes it by adding a check for a stalled status inside
Task.set_rerun.

Fix set_rerun to allow updating stalled task

---

ansible/roles/runner/tasks/setup.yml

Tuned is a profile-based system tuning tool that uses the udev device
manager to monitor connected devices, and enables both static and
dynamic tuning of system settings.
As the runner is virtual hosts for Vagrant machines it's good to have
it's kernel optimized for such workloads. To achieve this we need to
have tuned service enabled and running. Then, we need to activate a
virtual-host profile so tuned will make necessary changes in sysctl.
>> virtual-host decreases the swappiness of virtual memory and enables
>> more aggressive writeback of dirty pages.

Use tuned to make optimizations for runners

---

github/internals/entities.py
github/prci.py

When PR is forced pushed when test is running. The test will be
finished and then PR-CI will error out on status update step with
ERROR: __main__: Can't parse status data.
It is expected as the force push removed the status. But it
causes upload of data to sentry.io.
This patch adds EnvironmentError exception catching into execute
method of a Task class and raises ReferenceError when commit status
is not found. The error logs at a warning level, then runner's
execution proceeds.
Fixes https://github.com/freeipa/freeipa-pr-ci/issues/194

Fix failure after PR is forced pushed

---

templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

Qcow2 file backend can be significantly slow with cache mode 'none'
setting. This happens because the actual file data is fragmented. In
other words, the qcow2 file remain a sparse one with only short stroke
of allocation (for metadata).
So it's better to have an aggressive VFS RAM caching to have a better
random access speed.
The key aspect of this unsafe mode, is that all flush commands from the
guests are ignored. Using this mode implies that the user has accepted
the trade-off of performance over risk of data loss in the event of a
host failure. As we are using virtual machines only for a short period
of time it's safe to use it.

Changing volume caching from 'none' to 'unsafe'

---

scripts/prci_test_control.py

extend prci_test_control.py list task name length as longer names of
task used, shortened description field as not used much
Signed-off-by: Pavel Picka <ppicka@redhat.com>

Extend lenght of output characters

---

ansible/roles/automation/openclose_pr/tasks/main.yml

The Ansible role automation/openclose_pr is used to configure a
machine responsible for creating nightly PRs.
This role configures a cron job launching the script
openclose_pr.py every night at 00:23. The role currently does not
install crontabs package on the machine, which leads to deployment
failure.
This commit modifies the Ansible role so that it also requires
crontabs package installation.

open/close PR tool: install crontabs on the host

---

README.md
ansible/roles/runner/defaults/main.yml
ansible/roles/runner/files/mime.types
ansible/roles/runner/tasks/add_cloud_conf_files.yml
ansible/roles/runner/tasks/main.yml
ansible/roles/runner/tasks/setup.yml
doc/README.md
doc/images/overview.svg
doc/images/phase-C.svg
github/internals/entities.py
github/prci.py
requirements.txt
tasks/constants.py
tasks/index_template.html
tasks/remote_storage.py
tasks/root_index_template.html
tasks/tasks.py

Currently we are updating test results in Fedora infra where the results are
directly served as part of web server directory listing capabilities. This is
not case of AWS S3.
In order to simulate same environment we are generating "index.html" using
Jinja2 template and putting it into every directory. Then we upload particular
job directory using awscli (which does parallelism for us) under S3 bucket
"jobs" prefix (directory). Currently 2 awscli commands are needed in order to
set correct encoding for gzip files. Content types are set automatically using
"/etc/mime.types" file.
At the end we create root jobs index to list all jobs in the bucket.
There is also improvement that we can see PR#, author, task name and result together with UUID and filter using datatables.

remote_storage: switch from Fedora infra to AWS S3

---

tasks/common.py
tasks/vagrant.py

Sometimes when a task reaches timeout, cleanup of qemu processes
and Vagrant processes will not be performed. It will cause the lone
VMs to eat all of the available RAM.
This patch adds more process killing in termination of PopenTask.

Kill every child and qemu processes on termination

---

ansible/prepare_openclose_pr_tool.yml
ansible/roles/automation/openclose_pr/tasks/main.yml
doc/README.md
github/internals/entities.py
github/open_close_pr.py

Now the .freeipa-pr-ci.yaml it's just a symlink to a file that actually has the definition of the tests. This commit changes the tool that schedules the nightly tests.
The major change is that the "--prci_config" parameter now receives a relative path that will change to where the .freeipa-pr-ci.yaml link points

Making PR CI nightly tests definition editable by FreeIPA contributors

---

README.md
ansible/roles/runner/tasks/setup.yml

As the Fedora 28 doesn't have Python 2 bindings to firewalld and
ansible needs them by default to manage firewalld I'm removing
the firewalld configuration from the deployment process of the
runner.
Please note that as the part of FreeIPA team you should not worry
about it as our infrastructure has external firewall which manages
security rules.

Reverting firewalld configuration

---

tasks/constants.py
tasks/remote_storage.py
tasks/root_index_template.html
tasks/tasks.py

We are using jobs root index for a convenience of easily
finding and filtering jobs results, however getting data from
object metadata is very slow and time consuming which can result
in task being timed-out. DynamoDB as part of Amazon AWS stack seems
to be more suitable for this task.
As this functionality is not part of main PRCI job a run should not
fail on this.

root_index: switch from object metadata to AWS DynamoDB

---

ansible/roles/box/package/tasks/main.yml

At the end of creating new vagrant box template script
"create-template-box" fails with permissison denied as we do
not have privileges to halt vagrant machine. Adding "become" also
to "shutdown template VM" task solves the issue.

run "vagrant halt" during template create with privilege escalation

---

github/internals/entities.py
github/prci.py

Sometimes there may appear a wrong job definition in prci yaml
which causes the runners to fail.
In the following example we do not have "job" as a value of the task:
~~~
fedora-28/test_replication_layouts_TestCompleteTopologyWithCAKRA:
requires: [fedora-28/build]
priority: 50
job:
~~~
In case of such mistake we issue a warning and continue to another
task.
The fail is as follows:
~~~
Jul 28 09:40:04 ci-large-12 bash[8083]: Traceback (most recent call last):
Jul 28 09:40:04 ci-large-12 bash[8083]:   File "/root/freeipa-pr-ci/github/prci.py", line 314, in <module>
Jul 28 09:40:04 ci-large-12 bash[8083]:     main()
Jul 28 09:40:04 ci-large-12 bash[8083]:   File "/root/freeipa-pr-ci/github/prci.py", line 287, in main
Jul 28 09:40:04 ci-large-12 bash[8083]:     for task in …

prci: do not fail on wrong yaml indentation

---

ansible/roles/automation/openclose_pr/tasks/main.yml

The current configuration launches the nightly tests everyday. With this
fix, the nightly tests will be run only three times a week, on Monday,
Wednesday and Friday.

Scheduler for nightly tests: run on Mon, Wed and Fri

---

ansible/roles/machine/setup/defaults/main.yml
ansible/roles/machine/setup/tasks/install_packages.yml

Due to gssapi issue https://github.com/paramiko/paramiko/issues/1069
in paramiko we were using fixed paramiko==2.2.1 installed by pip. As
the fix for the issue above was backported to Fedora we start using
the recent F28 system package.

machine_template: switch to paramiko system package

---

ansible/roles/machine/setup/tasks/install_packages.yml
ansible/vars/ipa_branches/ipa-4-5.yml
ansible/vars/ipa_branches/ipa-4-6.yml
ansible/vars/ipa_branches/ipa-4-7.yml

As in the current master we stopped building python2 packages,
any attempt to uninstall them explicitly will fail. In this
case we differentiate uninstallation per branch.

Remove ipa python2 packages separately

---

github/internals/entities.py
github/prci.py

Fixes Issue #227 
The test definition should contain a dict for the topology definition. Usually we are using a repeated node,for instance:
`topology: *master_1repl`
If the test definition is missing the *, then the topology contains a string instead of a dict and PRCI crashes.
The fix properly handles this error.
When a test could not be run (wrong YAML content for instance), PRCI simply logs a message in the journal but the dashboard is not updated to reflect the issue.
This commit updates the task status to ERROR and prints "Test not executed: Wrong job definition " so that it does not get unnoticed.
Example:

Harden PRCI against wrong test definitions

---

tasks/tasks.py

https://github.com/freeipa/freeipa-pr-ci/issues/230
When a PRCI runner fails to publish the logs, the status on the PR page
simply states: "Failed to publish artifacts", but there is no information
about the machine where the runner failed. This PR adds the hostname, so
that is easy to check the machine and repair the issue.

PRCI: when runner fails to publish logs, print hostname

---

README.md
ansible/prepare_devel_test_runners.yml
ansible/prepare_test_runners.yml
ansible/roles/runner/tasks/autocleaner.yml
ansible/roles/runner/tasks/main.yml
ansible/roles/runner/tasks/setup.yml
autocleaner.py
requirements.txt

It happens that we hit an "out of disk space" issue on one of
our runners. This usually happens due to dangling libvirt images
which were left behind when VM erase was not completed completely.
Also for future automatic template generation we need to be able
to get rid of old template versions.
Autocleaner is doing the following:
1. Cleaning Vagrant boxes which are not used in any active branch
- go through current Vagrant boxes on particular runner
- get branch from box name
- perform GH GraphQL query to get PRCI yaml definitions files
- check if the box is defined anywhere
- if not, the box is deleted together with libvirt image
2. Clean dangling libvirt images when VM erase was not completed
completely.
- find old VM images in libvirt directory by UUID and delete them
3. If …

introduce runner autocleaner

---

ansible/roles/machine/setup/tasks/install_packages.yml
ansible/vars/fedora/29.yml
ansible/vars/ipa_branches/ipa-4-8.yml

Hello,
The intent of this PR is to create the Fedora 29 Vagrant Box used for PR CI to tests, upload it to Vagrant Cloud and add matching files.
1- Vagrant Image is already generated and uploaded to freeipa profile in Vagrant Cloud it can be found here:
https://app.vagrantup.com/freeipa/boxes/ci-master-f29
2 - I've tested this image with a build + simple_replication test, here are the test PR used for this and the results:
https://github.com/dhnunes/freeipa/pull/5

Fedora 29 Base Vagrant Box

---

templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

Vagrant master and replicas VMs memory consumption is over the limit and eventually causes the PRs to fail with OOM issue. This PR increases the master and replicas memory requirements up to 2750MB.

Vagrant: increase memory requirement for master and replicas VMs.

---

ansible/roles/machine/setup/tasks/install_packages.yml

Install firewalld in the machine setup, enable ssh firewall service and
mask firewalld.
For now firewalld gets masked after it has been configured to make sure
that tests that are not able to configure firewalld are still usable.
firewalld is configured using the command line tool. This has been done to
make sure that there is no Python2/3 import issue for the ansible firewalld
module is the firewalld imports are not available for this Python version.
The use of the command line tool has an advantage though: It is only one
call to enable all needed services at once instead of one call per service.
The firewalld service is masked. The mask should to be replaced with a
firewalld reload if all tests are able to configure the firewall.
The reload and also the configuration using the firewalld …

Install, configure and mask firewalld in the machine setup

---

ansible/create_template_box.yml
ansible/prepare_openclose_pr_tool.yml
ansible/roles/automation/nightly_pr/tasks/main.yml
ansible/roles/automation/setup/tasks/setup.yml
ansible/roles/automation/template_pr/tasks/main.yml
github/open_close_pr.py

This commit fixes the following bugs:
- Add missing "flow" variable in create_template_box.yml
- Remove "flow" ansible prompt variable since it is already
defined for every nightly/template PR definition
- Fix "with_items" indentation bugs
- Add missing ansible "libvirt services restart"
- Add missing "flow" var definition in open_close_pr.py
- Add "--force" on vagrant box remove to avoid prompt confirmation
- Install libguestfs-tools-c for Vagrant packager
- Install "requests" pip requirement
- Fix logger parameters mismatch
- Bump only the corresponding template version

open/close PR tool: fix several bugs

---

ansible/ping.yml
ansible/provision_ad.yml
ansible/roles/machine/provision/templates/hosts
ansible/roles/machine/provision/templates/ipa-test-config.yaml
ansible/roles/ping/tasks/main.yml
ansible/roles/runner/tasks/deploy_pr_ci.yml
ansible/roles/runner/tasks/setup.yml
ansible/roles/win-common/tasks/main.yml
ansible/roles/win-dns/tasks/main.yml
ansible/roles/win-domain/tasks/main.yml
ansible/roles/win-forest/tasks/main.yml
ansible/roles/win-ping/tasks/main.yml
ansible/roles/win-schema/files/sudo.schema
ansible/roles/win-schema/tasks/main.yml
ansible/variables.yml
tasks/tasks.py
tasks/vagrant.py
templates/ad.vars.yml
templates/vagrantfiles/Vagrantfile.ad

This commit implements new "provision_ad.yml" ansible playbook and new roles
such as packages, win-common, win-dns, win-domain, win-forest, win-ping, and
win-shcema. A new class "RunADTests" has been implemented to execute AD test
suites, and a new vagrant file "Vagrantfile.ad" defines the AD cluster, which
is composed by controller, ad, ad-child, master, and client0 VMs.
The implementation is based on three steps: a) prci deploy changes (new
packages and dependencies requirements, such as winrm modules), b) vagrant
cluster (using well-defined images for both Linux and Windows machines), and
c) software provisioning (software, schemas, the configuration of the scenario)

Add Active Directory infrastructure support

---

tasks/tasks.py

PR-CI publish artifacts fails when the runner gets out of space, but the systemd service
keeps running. This causes the next scheduled jobs to fail with the same reason. With this
commit, prci systemd service is disabled to avoid causing more troubles.

Stop prci systemd service when unable to publish artifacts

---

ansible/roles/builder/build/tasks/generate_build_version.yml

FreeIPA uses PEP-440 compliant version parsing. This spec has few
asumptions about about version structure. As result, 4.7.90test is lower
than 4.7.2. However, 4.7.90.dev is higher than 4.7.2.
Replica deployment code does verify that a replica is deployed against a
server that it at least the same or older than the replica itself. With
4.7.90test, replica never could be newer than 4.7.2 and thus the test is
failing.
Change the version used by the PR CI to comply with PEP-440.

Change version suffix from test to .dev

---

ansible/vars/fedora/27.yml

Used to build https://app.vagrantup.com/freeipa/boxes/ci-ipa-4-6-f27/versions/1.0.2.

Update Fedora 27 base image URL

---

tasks/tasks.py

Issue #273.
Create a file named `pr-ci-version` to be collected along other artifacts for debugging purposes.
Output can be found here: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/dd8e114c-889a-11e9-b2e3-fa163ed34842/

Store version of PR-CI used to run the tests

---

ansible/roles/builder/prepare/templates/mock-fedora-branched.cfg.j2
ansible/roles/builder/prepare/templates/mock-fedora-rawhide.cfg.j2
ansible/vars/fedora/27.yml
ansible/vars/fedora/28.yml
ansible/vars/fedora/29.yml
ansible/vars/fedora/30.yml
ansible/vars/fedora/rawhide.yml

FreeIPA master now requires Dogtag 10.7.  The @pki/10.6-nightly COPR
is not even built for f30, let alone with pki-10.7 packages.  Use
the @pki/master COPR on f30 to pull in the latest Dogtag builds.
(This if my first pr-ci PR... do images have to be explicitly rebuilt
after a change like this gets merged, or does it happen automagically?)

use @pki/master copr for f30

---

ansible/prepare_openclose_pr_tool.yml
doc/prscheduler.md

open_close_pr.py should be called with
--prci_def_dir ipatests/prci_definitions
not with
--prci_def_dir ipatests/prci_definition
Fix the doc to reflect the right path.

Fix prci_def_dir in the doc for nightly schedule

---

ansible/roles/runner/tasks/setup.yml

SystemMaxFileSize controls how large individual journal files may
grow at most; while SystemMaxUse controls how much disk space the
journal may use up at most. The latter is a better fit given the
storage availability PR-CI currently has in its runners.

Replace journald.conf setting used to control file size limit

---

github/internals/entities.py
github/prci.py

- Increase sleep time between status requests.
- Add a random component to back-off time to reduce concurrent requests by multiple runners.

Increase time between requests

---

autocleaner.py

File '.freeipa-pr-ci.yaml' usually points to a file from 'ipatests/prci_definitions' where the tests are actually defined.

Fetch test definitions from symbolic link

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Both nightly regressions ipa-4-6 and ipa-4-7 are running at the same time. This
is causing "Unable to create '/root/openclose_pr/freeipa/.git/index.lock': File exists
issues. This commit re-schedule ipa-4-6 nightly regression execution to a different slot.

Re-schedule ipa-4-6 nightly regression

---

whitelist.yml

In order to run PR-CI, Sumedh Sidhaye needs to be defined in
the whitelist.

Whitelist: add ssidhaye

---

ansible/roles/runner/tasks/autocleaner.yml

Runners are hitting 'out-of-space' issue. Something between 2 and 7GB are stored weekly.

Delete folders for jobs older than 3 days

---

ansible/roles/runner/tasks/autocleaner.yml
autocleaner.py

Based on our observations, journalctl logs keep growing until there
is no space left in the runner. This commit adds a function to
autocleaner script to clear journalctl logs and retain only the past
two days.
This commit also increases the autocleaner frequency to be executed
every day at 7am CET time.

Clear global journalctl as part of autocleaner

---

templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client

This way all versions used by PR-CI can be hosted, older or recent ones.
Latest image working: https://app.vagrantup.com/freeipa/boxes/windows-server-2016-standard-x64-eval/versions/20190801.01

Use freeipa account to store Windows boxes

---

ansible/roles/automation/setup/tasks/setup.yml

Add missing configuration to git fixing pull request creation.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/313

Set git user.name config to fix openclose_pr_tool

---

ansible/roles/automation/setup/tasks/setup.yml
ansible/roles/builder/prepare/tasks/main.yml
ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/setup/tasks/install_packages.yml
ansible/roles/runner/tasks/setup.yml

Changes:
- Replace dnf task to use loops instead of with_items
- Retry dnf tasks to fix repository synchronization issues 
---
These changes fix the following deprecation warning:
```
[DEPRECATION WARNING]: Invoking "dnf" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: "{{ item }}"`, please use `name: ['freeipa-*',
'python*-ipatests']` and remove the loop. This feature will be removed in
version 2.11. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
```
More info: https://docs.ansible.com/ansible/latest/modules/dnf_module.html
Issue: #295
---
When installing packages we might encounter a temporary network issue or fedora repo may fail to respond to dnf in time; …

Remove DNF warning and add retry when installing ipa* packages

---

ansible/roles/runner/files/prci.service
github/prci.py
tasks/common.py
tasks/vagrant.py

Issue: https://github.com/freeipa/freeipa-pr-ci/issues/309
A first attempt to fix this was done in bd3c3b3b874572b6f396c17c3b70032a6f242cb0 (https://github.com/freeipa/freeipa-pr-ci/pull/206).
Vagrant processes were killed before `VagrantCleanup` and `CloudUpload` had finished, causing more errors.
This commit removes the problematic call to kill vagrant processes and call libvirt to make sure all vms were destroyed and their storage deleted.
This also decreases the delay before the service gets restarted in case of an error.
---
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f266cbbc-f399-11e9-96c7-52540048449e/runner.log.gz
After publishing that output the runner continued to log locally:
```
Oct 20 21:34:25 …
```

Handle cascaded termination of vagrant processes

---

ansible/roles/automation/setup/tasks/setup.yml

Enable cron's option to direct Cron to send the job output to the system log using syslog(3).
The results should be accessible by executing `journalctl -ft CROND`.

Send cron output to system log

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/runner/tasks/main.yml
ansible/roles/utils/defaults/main.yml
ansible/roles/utils/tasks/enable_swap.yml

Enabling swap on both runners and vm might reduce some errors, even when the memory is enough to execute the tasks.
This commit adds a shared role to be used by playbooks during vm provisioning and runners deployment.
All tasks are idempotent operations.
Entry added to fstab to support host restarts.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/288

Enable swap on runners and virtual machines

---

ansible/roles/box/package/tasks/main.yml
ansible/roles/box/prepare/tasks/cleanup.yml
ansible/roles/box/prepare/tasks/main.yml
ansible/vars/fedora/31.yml
ansible/vars/ipa_branches/ipa-4-6.yml

- Fix tasks failing with recent Fedora hosts
- These changes are backwards compatible, but since Fedora 30 those changes
are required to continue to build images.
- Add Fedora 31 variables

Add fedora 31 box settings

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Definitions renamed by https://github.com/freeipa/freeipa/commit/c62bd1608e3a4aea27751826d7b8790367b1b5e3

Update cron jobs to reflect freeipa changes

---

ansible/roles/windows/ad-root/tasks/certificate-authority.yaml
ansible/roles/windows/ad-root/tasks/main.yml

Certificate Authority feature is required by test test_winsyncmigrate.py

Setup certificate authority on Windows Server

---

whitelist.yml

This account is used to trigger some tests against its fork.

Add freeipa-pr-ci2 to the whitelist

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/runner/handlers/main.yml
ansible/roles/runner/tasks/setup.yml
autocleaner.py
github/internals/entities.py
github/open_close_pr.py
github/prci.py
scripts/prci_test_control.py
templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client
templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

Changes required to provision PR-CI Fedora 30 runners and some other fixes.
Replace method used to load yaml file.
Method `yaml.load()` was deprecated, more info:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation
New templates have the required repositories configured properly and
this fallback is no longer needed.
This replaces the original PR https://github.com/freeipa/freeipa-pr-ci/pull/140
This reverts commit ddeb09a.
It was introduced as a temporary change for testing/debugging.
This is replacing original PR: https://github.com/freeipa/freeipa-pr-ci/pull/121
After https://github.com/hashicorp/vagrant/commit/f2bf18e56be36ed4bfbfe42fe20ab9147910ab3f
this variable can't be replaced.
This was added in the past, since latest vagrant version for Fedora 28
is 2.0.2 we …

Support Fedora 30 runners + other changes

---

ansible/roles/automation/setup/tasks/setup.yml
github/open_close_pr.py

Changes:
- Revert mistaken change
- Change made by 1b9671e.
- Method call replaced by mistake, this script is using a different
YAML library.
- Update prci-automation playbooks to support Fedora 30
- Follow-up of 56479ec.
- This includes a temporary fix for out-dated package `python3-github3py`.

Update prci-automation playbooks to support Fedora 30

---

ansible/roles/machine/setup/tasks/install_packages.yml

This package is an alias to `python3-PyYAML` or `python3-pyyaml`
packages depending on Fedora release.
This alias is not valid in rawhide and the packages are already
installed by other jobs:
- https://github.com/freeipa/freeipa-pr-ci/blob/master/ansible/roles/machine/setup/tasks/install_packages.yml#L62
- https://github.com/freeipa/freeipa-pr-ci/blob/master/ansible/roles/machine/setup/tasks/install_packages.yml#L72
This was necessary to build new rawhide template:
https://app.vagrantup.com/freeipa/boxes/ci-master-frawhide/versions/0.0.10

Remove PyYAML from packages to be installed

---

ansible/roles/runner/tasks/setup.yml

Install rubygem-winrm, rubygem-winrm-fs and winrm-elevated packages from
a temporary COPR repo.

Install missing packages required by vagrant to talk to Windows hosts

---

ansible/roles/machine/provision/tasks/main.yml
templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client
templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

__Changes__:
- Replace nfs with sshfs as vagrant's synced folder mechanism
- `vagrant-sshfs` plugin is already installed on the runners, this change
only replaces the mechanism defined in the vagrant files, disabling the
cache to make sure all files are synced, performance is not an issue in
this case.
- Touch ipa-test-config.yaml to work around ansible's selinux issue
- The issue affects nfs and sshfs (fuse) file systems, making sure the file
exists fixes the problem.
- This workaround is required only here because that is the only file under
`/vagrant/` that is generated by `template` module.
__Notes__: 
- I'm not removing NFS from source code at this moment to be easier to roll-back in case of some unexpected behaviour.
- SELinux workaround was tested using Fedora 31 with SELinux is …

Replace nfs with sshfs as vagrant's synced folder mechanism

---

ansible/roles/automation/setup/tasks/setup.yml

Replacing scratch build with a proper rpm from Koji.
Previous rpm was deleted, so that url was returning 404 (not found).

Fix koji rpm url

---

templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client
templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

Changes made in 11149e5de4140d1b62bd63dd6c23a5b1a9e7c917 didn't work with Fedora 27 guests, for now this is a quick and dirty fix while we still support Fedora 27 (AKA `ci-ipa-4-6-f27` template).
This addresses this https://github.com/freeipa/freeipa/pull/4120#issuecomment-573429906.

Revert NFS/SSHFS change for Fedora 27 guests

---

tasks/vagrant.py

New version of vagrant asks user for confirmation when destroying domains.
Since we run `vagrant destroy` in non-interactive way, it complains and
exits with status code 1, leaving the domains running.
Fixing it by adding "--force" option.
The problem can be seen in runner.log of any job:
```
2020-01-16 00:51:35,665     INFO  Executing: VagrantCleanup
2020-01-16 00:51:35,666     INFO  Destroying vagrant machines.
2020-01-16 00:51:35,667     INFO  Executing: Process "vagrant destroy"
2020-01-16 00:51:37,480    DEBUG  Vagrant is attempting to interface with the UI in a way that requires
2020-01-16 00:51:37,480    DEBUG  a TTY. Most actions in Vagrant that require a TTY have configuration
2020-01-16 00:51:37,481    DEBUG  switches to disable this requirement. Please do that or run Vagrant …
```

Fix `vagrant destroy` command.

---

README.md
ansible/prepare_devel_test_runners.yml
ansible/prepare_openclose_pr_tool.yml
ansible/prepare_test_runners.yml
ansible/roles/automation/box_hosting/files/404.json
ansible/roles/automation/box_hosting/files/app.py
ansible/roles/automation/box_hosting/files/gunicorn.service
ansible/roles/automation/box_hosting/files/gunicorn.socket
ansible/roles/automation/box_hosting/files/nginx.conf
ansible/roles/automation/box_hosting/tasks/main.yml
ansible/roles/runner/tasks/custom_vagrant_catalog.yml
ansible/roles/runner/tasks/deploy_pr_ci.yml
ansible/roles/runner/tasks/main.yml
ansible/roles/runner/templates/config.yml
github/prci.py
scripts/cache-vagrant-box.py
tasks/__init__.py
tasks/vagrant.py

These tasks install a web server (nginx) to host vagrant catalog and boxes.
To install boxes from this host just run the below command on your runner:
```
$ export VAGRANT_SERVER_URL='http://URL_TO_THIS_PRCI_AUTOMATION_HOST'
```
Request to http://prci-automation/freeipa/ci-master-f30 will return the catalog
you can use any combination of username/boxname.
Requests to boxes not available (not downloaded) will be redirected to
vagrantup.com.
To download a box to be hosted by prci-automation you need to run:
```
$scripts/cache-vagrant-box.py {username} {boxname} {version}`
```
E.g: `scripts/cache-vagrant-box.py freeipa ci-master-f31 0.0.1`

Host vagrant catalog on prci-automation

---

ansible/roles/machine/setup/defaults/main.yml
ansible/roles/machine/setup/tasks/install_packages.yml
ansible/vars/flows/389ds.yml
ansible/vars/flows/ci.yml
ansible/vars/flows/pki.yml
ansible/vars/flows/testing.yml
ansible/vars/ipa_branches/ipa-4-6.yml
ansible/vars/ipa_branches/master.yml

This reverts commit f181d0b, where SELinux had to be disable after an issue with Ansible, a workaround to that issue was added in 3773203.
Enable COPR repo only for master branch templates. Recent changes to COPR made [@freeipa/freeipa-master](https://copr.fedorainfracloud.org/coprs/g/freeipa/freeipa-master/packages/) the only repo to host freeipa's dependencies. Other repos include freeipa packages.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/266

Enable SELinux in permissive mode

---

tasks/vagrant.py

Follow-up for 70e0ab24c1c8d8d435831c1324821ec4561cef97.
This was tested in parallel infra: https://github.com/freeipa-pr-ci2/freeipa/pull/130

Fix date comparison when boxes where already installed in the system

---

ansible/roles/automation/box_hosting/tasks/main.yml
ansible/roles/runner/tasks/custom_vagrant_catalog.yml
ansible/roles/runner/tasks/main.yml

- Add missing vagrant catalog tasks
- SELinux was blocking nginx to talk to gunicorn socket.
- Gnunicorn service wasn't enabled nor started after `gunicon.socket` service was started.
- Reset environment variable to use Vagrant's default catalog
- This can be used to easily rollback PR-CI to use Vagrant's catalog if `prci-automation` is not available.

vagrant catalog provisioning fixes and improvements 

---

github/internals/gql/queries.py
github/internals/gql/util.py

Github sorts commits by their 'author date', not by their order in tree, thus last commit it's not always the head of a pull request.
This returns the commit matching its `oid` (hash) with pull request's `headRefOid` value.
Last 250 (maximum allowed) commits from a given pull request must be fetched to keep the number of API requests the same as it is.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/264
Pull request used for testing this: https://github.com/netoarmando/freeipa/pull/47
---
@frasertweedale I was writing the commit message for the solution we discussed, then I decided to take another look to github's doc and I've found the `headRefOid` property. :-D

Return head commit from pull requests

---

tasks/index_template.html
tasks/remote_storage.py

Replace hard coded value with owner of the monitored freeipa repo.
Remove unnecessary functions used to build template's data dictionary.
--- 
Example of the output after this changes: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/4abff61a-51bb-11ea-bbac-5254002d2921/

Remove hard coded repo owner from index html

---

ansible/roles/machine/provision/tasks/main.yml

The dependencies are required for testing ipa-4-6 branch
* ntpdate is required by AD trust related tests
* sssd-tools is required by new tests in sssd

install tests dependencies specific to Fedora 27

---

ansible/roles/automation/nightly_pr/defaults/main.yml

After [this change](https://github.com/freeipa/freeipa/commit/c1660a4c023a28cdad40720fd91d7e57870b4808) in freeipa the scenarios changed to test `ipa-4-8` branch with latest and previous releases of Fedora. This commit updates prci-automation crontab to reflect that change.

Update nightly jobs to include new ipa-4-8 test

---

github/internals/entities.py

This has been changed after a peak of occurrences of this issue that might be related to jobs jumping from one runner to another.

Improve log to help problem investigation

---

ansible/roles/automation/nightly_pr/defaults/main.yml

* Disable ipa-4-7 nightly run 
FreeIPA 4.7.5 is the last release in ipa-4-7, thus no more pull requests will target ipa-4-7 branch.
More info:
https://lists.fedorahosted.org/archives/list/freeipa-users@lists.fedorahosted.org/thread/FYUNCFWHY25OESUFDAOJWL6ELYQJ5FQ2/
**Note**: This is already in production, cron was updated to not trigger `ipa-4-7` runs.
* Move test executing time to not clash with another
`testing_master_testing` time was clashing with `testing_master_rawhide`.

Update nighlty runs crontab

---

ansible/roles/box/package/tasks/main.yml
ansible/roles/box/prepare/tasks/main.yml
ansible/roles/builder/prepare/templates/mock-fedora-branched.cfg.j2
ansible/roles/builder/prepare/templates/mock-fedora-rawhide.cfg.j2
ansible/roles/utils/defaults/main.yml
ansible/roles/utils/tasks/enable_swap.yml
ansible/vars/fedora/rawhide.yml

- Bump rawhide release
- Replace fallocate with dd
Due to a known bug in some filesystems where fallocate file is raising errors when trying to enable swap.
- Disable tmpfs plugin in mock    
Build with it enabled is failing for Fedora 32 (Beta) and Rawhide (33).
Stable `mock` versions as of today:
mock-2.1-1.fc30
mock-2.1-1.fc31
mock-2.2-1.fc32
mock-2.2-1.fc33
- Add tags to tasks for helping with template generation
They can be used to when template generation need to be retried. E.g:
```
$ ./create-template-box --skip-tags "upload_box,download_rawhide_box"
```

Changes required to build Fedora 32+ templates

---

ansible/roles/machine/provision/tasks/main.yml

NM periodically updates contents of /etc/resolv.conf putting
dhcp-provided DNS server on top of the list which breaks the
tests relying on DNS data provided by IPA server.

prevent NetworkManager from updating /etc/resolv.conf

---

ansible/roles/box/prepare/templates/Vagrantfile.j2

Because of QEMU Session enabled by defailt, a failure occurs with if Vagrantfile contains:
` test_vm.vm.network :private_network, :ip => "172.16.0.2" ` or similar. Can be solved by
setting libvirt.qemu_use_session = false in Vagrantfile.
This commit adds the changes to the Vagrantfile jinja template.

template: disable qemu session enabled by default

---

ansible/roles/machine/provision/tasks/main.yml

This reverts commit df43a00f66dac8daa6f8c6098706ce976096043d.
The commit is causing issues with dnf install. We are reverting this commit for now
until we can investigate what is causing the problem.
We have tested freeipa-pr-ci without this commit here:
https://github.com/bhavikbhavsar/freeipa/pulls
and all jobs are passing.

Revert "prevent NetworkManager from updating /etc/resolv.conf"

---

tasks/common.py
tasks/vagrant.py

In the event of vagrant suspending hosts, runner rebooted or connection lost between vagrant hosts and runner PRCI fails and return error to Github.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/327
---
Log output when a vagrant machine is suspended:
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/40022da4-a5f5-11ea-a617-5254000d65ad/
Log output if vagrant process is killed (SIGTERM):
http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3617ddd6-a5fd-11ea-b190-5254000d65ad/runner.log.gz

Force test to fail if provisioning fails

---

tasks/vagrant.py

Current boxes are larger than they used to be and small runners can't handle much more than 4 boxes.

Keep only 3 boxes in the runners

---

ansible/roles/machine/setup/tasks/install_packages.yml

Those packages version numbers were crashing with the ones built for testing.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/378

Remove all freeipa-* packages from template

---

ansible/roles/windows/ad-root/tasks/main.yml
ansible/roles/windows/ad-subdomain/tasks/main.yml

As Fedora 32's default crypto policy does
not support RC4 any more, thus AES encryption
enabled on AD side.
Fixes: https://pagure.io/freeipa/issue/8294

Enforce AES encryption

---

tasks/vagrant.py

Production runners require 2 boxes only (latest master and ipa-4-8 branches). Nightly runners are running close to the threshold to hit out of space issues.

Keep only 2 boxes

---

tasks/tasks.py

Data from nightly runs were not uploaded to dynamodb because they are triggered from a fork.

Update job data from nightly runs

---

ansible/roles/machine/setup/tasks/install_packages.yml

Webui tests started to fail after the new release of geckodriver (v0.27.0).
As a temporary solution geckodriver has to be downgraded.
Issues:
- https://github.com/freeipa/freeipa-pr-ci/issues/388
- https://github.com/mozilla/geckodriver/issues/1756
- https://pagure.io/freeipa/issue/8473

Force geckodriver version

---

ansible/roles/machine/provision/tasks/main.yml
tasks/tasks.py
templates/ad.vars.yml
templates/run_pytest.vars.yml

Setting `selinux_enforcing: true` as an argument to a job definition will change the SELinux mode to `enforcing` during provisioning phase.
Issue #391 
Testing run: https://github.com/netoarmando/freeipa/pull/60

Add support to change SELinux mode to enforcing

---

templates/vagrantfiles/Vagrantfile.ipaserver

New check added by commit https://pagure.io/freeipa/c/cfad7af35dd5a2cdd4081d1e9ac7c245f47f1dce?branch=master
requires 1.6GB available.
Setting the same amount as used by other vms without any issue.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/393
---
Test run: https://github.com/freeipa-pr-ci2/freeipa/pull/411

Increase memory required by vm

---

ansible/roles/automation/nightly_pr/defaults/main.yml

This enables the scenarios proposed by the related issue to run weekly on Monday, Wednesday and Friday.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/391

Enable SELinux in Enforcing mode nightly runs

---

ansible/vars/fedora/33.yml

Fedora 33 was released, nightly composes are not necessary for it anymore.

Update settings for Fedora 33

---

ansible/roles/machine/provision/tasks/main.yml

The freeipa-fas package must not be installed when running PRCI tests.
See the issues triggered by its presence:
https://pagure.io/freeipa/issue/8570
https://pagure.io/freeipa/issue/8569
Fixes: https://github.com/freeipa/freeipa-pr-ci/issues/400

Provision machine: do not install freeipa-fas package

---

ansible/roles/builder/prepare/templates/mock-fedora-rawhide.cfg.j2
ansible/vars/fedora/rawhide.yml
scripts/cache-vagrant-box.py

- Print and compare checksum when adding new box
>     Update script used to download a box to the locally hosted Vagrant
>     catalog to compare box's sha1sum with the one availble on the original
>     registry, saving time when publishing new box templates.
- Normalize Rawhide definitions
>     * Update COPR repos for rawhide to don't use release numbers, build stage
>     was failing in recent (f34) release target.
> 
>     * Add 389 COPR repo to rawhide mock definition, this way branched and
>     rawhide definitions look the same.
> 
>     * Include disabled variables to rawhide.yml to provide an easier way to
>     check what's availble when building a new template.

Normalize rawhide definitions + Improve tool used to store templates

---

ansible/roles/builder/build/tasks/create_spec.yml

FreeIPA spec file template already contains autoconf use, no need to add
another one.
Do not replace Version: line, replace @VERSION@ in IPA_VERSION
definition alone. IPA_VERSION macro is reused across the spec file.
Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>

Modernize spec file modifications

---

ansible/roles/builder/build/tasks/create_spec.yml

FreeIPA 4.6 spec file needs to call autoreconf. Later releases already include autoreconf.

Add autoreconf do ipa-4-6 spec file

---

ansible/roles/machine/provision/tasks/main.yml

Fedora 33 switched its default DNS resolver to systemd-resolved, previously the task was getting the DNS server from /etc/resolv.conf, but for Fedora 33 that value is a loopback, breaking IPA installation because that address is used to define a DNS forwarder.
Testing this here: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/f6a1b546-38be-11eb-95c6-5254000d65ad/

Fix Fedora 33 DNS forwarder

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/provision/templates/ipa-test-config.yaml

An additional task was necessary to check whether var was skipped or not.
From Ansible doc:
> Ansible always registers something in a registered variable for
> every host, even on hosts where a task fails or Ansible skips a task
> because a condition is not met.
---
This is a follow-up of https://github.com/freeipa/freeipa-pr-ci/pull/407 because of an error reported at https://github.com/freeipa-pr-ci2/freeipa/pull/576#issuecomment-741628984.
Test execution: (https://github.com/netoarmando/freeipa/pull/66)
* `fedora-latest-f32/test_upgrade`: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/3c0275d8-3a60-11eb-b478-5254000d65ad
* `fedora-latest-f33/test_upgrade`: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.co …

Fix Ansible skipped variable when registering dns_server

---

ansible/roles/builder/collect/tasks/main.yml

Logs were collected when RPMs are built; however, if there was an issue while building SRPMs no logs were collected.
This creates two folders to store the logs for both stages.
---
* Successful build output: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/82da60de-35aa-11eb-b65a-5254000d65ad/
* Forced error during `builder/build : create srpm`: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/c13a7846-35af-11eb-b65a-5254000d65ad/ 
* Forced error during `builder/build : create rpms`: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/716598c4-35b8-11eb-b65a-5254000d65ad/

Collect mock --buildsrpm logs

---

ansible/roles/machine/provision/tasks/main.yml

Replace task command to fetch DNS sever from `resolvectl dns` command, this will not return whitespaces.
Execute `grep -m1` to limit the number of lines to 1.
Execute `tr` to remove possible spaces.
Issue https://github.com/freeipa/freeipa-pr-ci/issues/410
---
Test runs:
- `fedora-32/test_webui_users`: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/7f901ebe-3e24-11eb-9129-5254000d65ad
- `fedora-33/test_webui_users`: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/ccc97ac6-3e2a-11eb-9129-5254000d65ad
- `fedora-rawhide/test_webui_users`" http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/d0da5f62-3e30-11eb-9129-5254000d65ad

Fix resolvectl task returning white spaces

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Disable nightly runs for ipa-4-8 branch and enable ipa-4-9 to replace them.

Replace ipa-4-8 with ipa-4-9 nightly jobs

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/provision/templates/resolv.conf

File /etc/resolv.conf should not be edited in PR-CI.
* On distros that use NetworkManager to manage resolvers (i.e. Fedora 32)
it is useless as NM overwrites contents of /etc/resolv.conf.
* On distros where user manages resolvers by editing resolv.conf this
would break  tests which do packages installation before IPA server
installation. As resolv.conf created by ansible contains only records
for IPA server and replicas, package manager will not be able to
resolve repository host name.
* On distros that use systemd-resolved (i.e. Fedora 33) /etc/resolv.conf
is a symlink to a file generated by resolved. NM does not alter
symlinks by design, but PR-CI replaces symlink with a regular file and
NM starts to manage /etc/resolv.conf which creates a non-standard
system installation.

Do not write resolv.conf when provisioning test VMs

---

autocleaner.py

Fixing two issues in autocleaner.py:
* Crash while removing old jobs dirs (#422)
* `--jobs_dir_exp` option was not respected, all jobs dirs were removed

Fix autocleaner

---

ansible/vars/fedora/34.yml
ansible/vars/fedora/rawhide.yml

Fedora 34 is still under development, this is a temporary definition file.
Fedora Rawhide now targets Fedora 35.

Add Fedora 34 template and bump rawhide

---

ansible/roles/machine/provision_ipaserver/tasks/main.yml
ansible/roles/machine/provision_ipaserver/templates/ui_test.conf.j2
tasks/tasks.py
templates/run_pytest.vars.yml

Templates and ansible playbooks for ca-less provisioning of ipa server
used for WebUI testing. Certificates are generated locally and provided
to the installer.

Provision ipaserver in ca-less mode for WebUI tests.

---

ansible/vars/fedora/34.yml

Fedora 34 was released, nightly composes are not necessary for it anymore.

Update settings for Fedora 34

---

ansible/roles/automation/nightly_pr/defaults/main.yml
ansible/roles/automation/nightly_pr/tasks/main.yml
github/open_close_pr.py

Add a --reviewer option to the open_nightly_pr subcommand
of open_close_pr script.
When a --reviewer is provided, a review of the nightly PR
is requested from the reviewer. This helps tracking who should
investigate which nightly.

Schedule nightly PR: add a review request

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Change the day of the week testing_master_testing is executed
so that it is the same day as testing_master_testing_selinux.
Signed-off-by: François Cami <fcami@redhat.com>

Execute testing_master_testing on Wednesdays

---

ansible/roles/windows/ipa-ad-data/tasks/ad-root.yml

1. Create posix user create a user without gid
2. Create posix user with gid but no corresponding group.
3. Create nonposix user with a primaryGroupID that is not the default one
Signed-off-by: Sudhir Menon <sumenon@redhat.com>

Adding new ADusers and groups required for auto-private-group tests

---

ansible/roles/automation/nightly_pr/defaults/main.yml

commit 6f007d5 changed the nightly owner for one of the
testing_master_previous runs, but this results in the same
key used for both runs.
Merge them instead (they have the same owner) and define the
2 weekdays in a single crontab entry.

Nightly tests: merge testing_master_previous in the crontab

---

ansible/roles/machine/cleanup/tasks/clean_vagrant_temp.yml
ansible/roles/machine/cleanup/tasks/main.yml
ansible/roles/machine/setup/defaults/main.yml
ansible/roles/machine/setup/tasks/configuration.yml
ansible/roles/machine/setup/tasks/install_packages.yml

**Changes**: 
* Remove left-over file (/etc/sysconfig/network-scripts/ifcfg-eth1) used by Vagrant during image generation.
* Pin `pytest-html` version to fix conflict when dnf updates all packages.
* Remove unnecessary `fedora-cisco-openh264` repo.
Issue: https://pagure.io/freeipa/issue/8959
---
Image generated after this: https://app.vagrantup.com/freeipa/boxes/ci-ipa-4-6-f27/versions/1.0.5/
Pull request testing it: https://github.com/freeipa-pr-ci2/freeipa/pull/1247

Fix ipa-4-6-27 image

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Ganna volunteered for testing_master_previous, that launches on Tuesday.
Update the owner accordingly.

Nightly owners: assign testing_master_previous to gkaihorodova

---

ansible/roles/machine/setup/tasks/install_packages.yml

Add package to enable `cifs` module.
Issue: https://pagure.io/freeipa/issue/9087

Install kernel-modules package

---

tasks/common.py

Python 3.8.7 was already printing warning about that when import Callable from collections:
```
DeprecationWarning: Using or importing the ABCs from 'collections'
instead of from 'collections.abc' is deprecated since Python 3.3,
and in 3.9 it will stop working.
```
Fedora 35 runners have Python 3.10 so this is needed to support PR-CI.

Fix deprecated import shortcut

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/utils/tasks/bash_settings.yaml

enable-bracketed-paste is enabled by default since bash-5.1. When set to On,
readline will configure the terminal in a way that will enable it to insert
each paste into the editing buffer as a single string of characters, instead
of treating each character as if it had been read from the  keyboard. This is
affecting some of our automated tests:
pexpect.exceptions.ExceptionPexpect: Program exited with an unexpected state:
Unexpected output at program exit: '  \x1b[?2004l\r'
This commit adds bash_settings task group as part of utils role so that
we can disable back bracketed-paste mode and maybe other settings in the
future.

Disable bash bracketed-paste mode

---

ansible/roles/machine/provision/tasks/main.yml
tasks/tasks.py
tasks/vagrant.py
templates/run_pytest.vars.yml

Introduce fips bool variable and its handling, implement FIPS setup to          
provisioning playbooks. Include check to ensure that FIPS mode is                
initialized correctly prior to launching the test phase.                           
Add support for reloading all machines from vagrant's side (this halts             
all the machines, starts them up and reestablishes shared folder).                 
Reload can be triggered by creating a REBOOT_READY file in the vagrant            
shared folder before the test phase (either in provisioning or upping             
phase).                                                                           

Add support for FIPS mode

---

ansible/roles/utils/tasks/enable_swap.yml

Fedora cloud images started to come with swap enabled in version 35.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/456
Test results: https://github.com/netoarmando/freeipa/pull/69

Disable swapfile creation if not Fedora <= 34

---

ansible/roles/machine/cleanup/tasks/clean_mac_addresses.yml

Fedora 36 removes the NetworkManager legacy configuration file support
(ifcfg files). As the ifcfg files are not present for Fedora 36, the
automation to create new vagrant template boxes is broken.
With this commit, errors from clean_mac_addresses.yml when trying to
fetch ifcfg files are simply ignored.

Ignore errors from gathering list of ifcfg files

---

ansible/roles/box/package/tasks/main.yml

Otherwise, vagrant package might generate broken vm, without ssh.

Wait 30 seconds after vm is rebooted

---

ansible/roles/builder/build/tasks/create_rpms.yml
ansible/roles/builder/prepare/templates/mock-fedora-branched.cfg.j2
ansible/roles/builder/prepare/templates/mock-fedora-rawhide.cfg.j2
ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/setup/defaults/main.yml
ansible/roles/machine/setup/tasks/configuration.yml
doc/README.md
tasks/tasks.py
templates/run_pytest.vars.yml

Replace defined-during-image-build definitions of COPR repos with a "copr" and "enable_testing_repo" vars that can be set in the test definitions file.
E.g:
```
fedora-latest/build:
requires: []
priority: 100
job:
class: Build
args:
enable_testing_repo: true
copr: '@pki/master'
git_repo: '{git_repo}'
git_refspec: '{git_refspec}'
template: &ci-master-latest
name: freeipa/ci-master-f35
version: 0.0.5
timeout: 1800
topology: *build
```
Also, the "build" job needs to set those variables too.
And `update_packages` must be set to `True` when setting `enable_testing_repo` or `copr`; otherwise, packages available on those repos wouldn't be updated.

Set custom COPR repo via test definition files

---

ansible/roles/builder/prepare/templates/mock-fedora-branched.cfg.j2

Removed in 4533d7bcf1fb4c407e2735fe5c0f6b0df6c5ecde by mistake, this is necessary (disabled by default) when running jobs with `enable_testing_repo = True`.
A new vagrant box will be provided with this fix.

Add 'updates-testing' repo back to mock config

---

ansible/roles/builder/build/tasks/create_rpms.yml
ansible/roles/machine/setup/defaults/main.yml

> When running rawhide Ansible's variable `ansible_distribution_release` is empty, it was expected to be `Rawhide`. So, instead of using that this change is adding a task to check the content of `/etc/fedora-release` file.
> Old 1.22.x version was Python 2.7 compatible.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/467
---
This has been tested here: https://github.com/netoarmando/freeipa/pull/71

Fix COPR and Python dependencies in Fedora Rawhide

---

ansible/roles/automation/nightly_pr/defaults/main.yml

New nightly tests will be launched:
ipa-4-10:
- previous: Monday 08:00
- latest: Tuesday 11:00
- lastest selinux: Thursday 11:00
sssd: Sunday 08:00

Nightly scheduler: add ipa-4-10 nightlies

---

autocleaner.py

**fix(autocleaner): featching of prci def files from new branches**
the autocleaner was failing on fetching prci def files from branch
ipa-4-10.  This happened because the files were downloaded from
PR-CI user's freeipa fork and not from the main "freeipa" organization.
This happened as the query was starting with 'viewer' query, which
represents the currently logged-in user.
This patch is changing the query to always check the main
freeipa/freeipa repo and thus it won't fail if the token owner repo
doesn't contain some new branch.
**fix(autocleaner): filter out prci_checker files**
PR: https://github.com/freeipa/freeipa/pull/6301
Added new files to prci_definitions folder which are not PR-CI defition
files. Thus these needs to be filtered out otherwise the autocleaner
will crash on …

fix: autocleaner failing on getting prci def files

---

whitelist.yml

Add a new contributor to the whitelist.

Add Erik Belko (b3lix) to the whitelist

---

whitelist.yml

Add Scott to the whitelist
in order to be allowed to trigger PRCI tests

Add spoore1 to the whitelist

---

ansible/roles/windows/ipa-ad-data/tasks/ad-root.yml

Added user with possix attributes defined.
For RFE Aduser is required with possix attribute.
Where users uid and gid is same and group has info attribute defined.
Related : https://bugzilla.redhat.com/show_bug.cgi?id=2062689#c6
Signed-off-by: Anuja More <amore@redhat.com>

Added user with possix attribute.

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Due to organizational restructuration, assign Sumedh's nightly runs to Ganna.

Assign ssidhaye's jobs to gkaihorodova

---

templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client
templates/vagrantfiles/Vagrantfile.adroot_adchild_adtree_master_1client
templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

The `dnf install` commands were consuming more memory and failing the related tasks.
More info: https://github.com/freeipa-pr-ci2/freeipa/pull/2228#issuecomment-1328874034
Controller now have the same amount as client vms.
The `memory` property was also updated/added to all templates. 
Later, the definitions at the freeipa repo must be updated.
However, based on the numbers here, nothing should change. Those numbers, memory and cpu, are used to check if a job can be run. Since we have only two types of runners, jobs will fall in the same sized runner as now.
Small runners have, in average, 6.9Gi free when in idle; and big runners 14Gi.
I'm going to deploy this right now to the nightly runners and re-run some f36 PR.

Increase controller memory

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/runner/tasks/setup.yml
ansible/roles/utils/tasks/enable_swap.yml

'warn' parameter for 'args' was deprecated and removed in newer Ansible verions (e.g. the one on Fedora 37+).
Removal is required for successful run of runner deployment playbooks.

fix: remove unsupported Ansible parameter 'warn'

---

ansible/create_template_box.yml
ansible/roles/box/prepare/tasks/cleanup.yml
ansible/roles/machine/workarounds/tasks/configure_sunrpc_nfs_port.yml
ansible/vars/fedora/39.yml
ansible/vars/fedora/rawhide.yml
ansible/vars/ipa_branches/ipa-4-11.yml
vagrant/atlas.py

**Add Fedora 39 vars and bump rawhide**
As a prep for creating new boxes for ipa-4-11 and master branches.
adjustments for building f39 ipa box
**Applying the workaround did not work, thus it was commented out.**
+ some cleanup
**box uploader to run on newer Python**
collections.Mapping moved to collections.abc module thus the code needed
to be adjusted otherwise it crashed.

Add Fedora 39 vars and bump rawhide + some fixes to make it build

---

ansible/cleanup_runner_disk.yml
ansible/prepare_devel_test_runners.yml
ansible/prepare_openclose_pr_tool.yml
ansible/prepare_test_runners.yml
ansible/roles/automation/setup/tasks/main.yml
ansible/roles/box/prepare/tasks/main.yml
ansible/roles/builder/build/tasks/main.yml
ansible/roles/builder/cleanup/tasks/main.yml
ansible/roles/machine/cleanup/tasks/main.yml
ansible/roles/machine/setup/tasks/main.yml
ansible/roles/machine/workarounds/tasks/main.yml
ansible/roles/runner/files/prci.service
ansible/roles/runner/tasks/custom_vagrant_catalog.yml
ansible/roles/runner/tasks/deploy_pr_ci.yml
ansible/roles/runner/tasks/main.yml
ansible/roles/runner/tasks/setup.yml
templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client
templates/vagrantfiles/Vagrantfile.adroot_adchild_adtree_master_1client
templates/vagrantfiles/Vagrantfile.build
templates/vagrantfiles/Vagrantfile.ipaserver
templates/vagrantfiles/Vagrantfile.master_1repl
templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

These are fixes to be able to deploy and run task on F39 runner.
Rebased on: https://github.com/freeipa/freeipa-pr-ci/pull/493 
**fix: use ansible.compatibility_mode = "2.0" in Vagrantfiles**
Needed with newer version of Ansible (on F39) so that generated
Ansible inventory is using ansible_host, ansible_user, ansible_password
instead of ansible_ssh_{host,user,password}.
I.e. so that prci can connect to Windows hosts.
**fix: use hashicorp vagrant**
Instead of the one on Fedora.
Reason: atm Fedora 39 has Vagrant 2.3.4, but we need 2.3.9 to fix winrm
auth issue:
```
ERROR warden: Error occurred: An error occurred executing a remote WinRM command.
Shell: Cmd
Command: hostname
Message: Digest initialization failed: initialization error
```
**fix: cleanup vagrant installation**
- remove support …

Fixes for F39 runner

---

autocleaner.py

The method ruamel.yaml.safe_load(yml_file) has been deprecated with ruamel.yaml 0.15.0. Use instead:
yaml = YAML(typ='safe', pure=True)
yaml.load(...)
Fixes: https://github.com/freeipa/freeipa-pr-ci/issues/495

autocleaner: replace calls to deprecated ruamel.yaml.safe_load method

---

ansible/roles/automation/nightly_pr/defaults/main.yml

ipa-4-10 branch is currently tested on fedora 37 (labelled as
ipa-4-10_previous) and 38 (labelled as ipa-4-10-latest).
As fedora 37 is EOL, stop the tests on f37.
The tests for ipa-4-11 branch will now be scheduled:
- Monday 8h for ipa-4-11 latest (fedora 39)
- Friday 7h for ipa-4-11 latest with selinux (fedora 39)
Ticket: FREEIPA-10719

Nightly tests schedule: add tests for ipa-4-11

---

ansible/create_template_box.yml
ansible/roles/box/prepare/templates/Vagrantfile.j2
ansible/roles/machine/setup/tasks/configuration.yml
ansible/vars/fedora/40.yml
ansible/vars/fedora/rawhide.yml
ansible/vars/ipa_branches/ipa-4-12.yml

The cloud base vagrant image for Fedora 40 has a small disk size (5G) by default.
Increase to 20G, grow the partition and extend the BTRFS to the max siz available.

Add fedora 40 vars and ipa-4-12 branch

---

whitelist.yml

Add Jarl Gullberg (Nihlus) to the contributors list, so that his new PRs automatically trigger gating tests.

Contributor list: add Nihlus

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Changes compared to the current schedule:
- ipa-4-10_latest is removed (we keep ipa-4-10_latest_selinux)
- ipa-4-9_latest is removed (we keep ipa-4-9_latest_selinux)
- ipa-4-12_latest is added on Tuesdays, assigned to b3lix
- ipa-4-12_latest_selinux is added on Saturdays, assigned to b3lix

Nightly tests: update the schedule

---

ansible/group_vars/all/vars.yml
ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/provision/templates/hosts
ansible/roles/machine/provision/templates/ipa-test-config.yaml
tasks/tasks.py
templates/run_pytest.vars.yml
templates/vagrantfiles/Vagrantfile.ipa_ipa_trust

Add multidomain topology for ipa-replica-client
IPA multidomain topology is added for domain :
ipa.test and trustedipa.test
Related : https://issues.redhat.com/browse/FREEIPA-11087

Test multidomain

---

ansible/roles/machine/provision/tasks/main.yml

When the test machines are provisioned, the hostname must be set (otherwise the default hostname "localhost" is used.
The current logic relies on the inventory hostname being either master / client / replica / controller / trustedmaster / trustedclient / trustedreplica but depending on the Vagrant file the inventory hostname can also be client0 replica2 etc...
In this case the hostname is not set.
Change the logic to set the hostname to xx.ipa.test if the inventory_hostname does not contain trustedxx and to xx.trustedipa.test if the inventory_hostname contains trustedxx.

Provision machines: fix hostname logic

---

ansible/roles/windows/sshd/tasks/main.yml

The playbook installing cygwin openssh contains a loop trying multiple mirrors until one of them succeeds. Ansible changed behavior and the result.failed variable is not set if the iteration succeeded.
Default to false if not set, so that the loop continues if the last iteration failed but is skipped if it succeeded.
Resolves: https://github.com/freeipa/freeipa-pr-ci/issues/512

Cygwin installation: define default value in the loop

---

ansible/roles/machine/provision/tasks/main.yml

Fedora 41 ships with dnf5 and the command
dnf config-manager --set-enabled updates-testing
should be replaced with
dnf config-manager setopt updates-testing.enabled=1

On F41+, dnf config-manager --set-enabled does not exist

---

whitelist.yml

The user was added in lowercase but the allow list is case-sensitive.

Allow list: fix case for KoRORland
