github/prci.py
requirements.txt

github runner: log errors with sentry.io

---

github/prci_github/internals.py

The only synchronization mechanism is GitHub statuses API so there's always
chance that two (or more) runners will process one task. In such situation only
the last runner that has taken the task will report the results. The other
runners will throw the results away and report that this situation happened.

github: Detect and report task processing race

---

github/prci_github/internals.py

This will help detect stale or stuck tasks.

github: Add task processing start time and date

---

github/prci_github/internals.py

github3.github3.PullRequest is wrapped in prci_github.internals.PullRequest

github: Fix attribute error

---

github/prci_github/internals.py

There's quite high consuption of GitHub API requests due to combination of
following 3 reasons:
- Right now most of PRs don't have tasks configuration file.
- PRs are checked quite often.
- 404 Not Found answer is not cached.
To workaround this tasks configuration files are fetched from GitHub WebUI.

github: Get tasks file over web interface instead of API

---

ansible/prepare_devel_test_runners.yml
ansible/roles/runner/defaults/main.yml
ansible/roles/runner/templates/config.yml
github/prci.py

Now, to change the value of task delay time, you can modify the prepare_devel_test_runners.yml::task_backoff_time variable. This will affect only in the development environment.
Fixes: https://github.com/freeipa/freeipa-pr-ci/issues/33

Changing how to setup the task delay time

---

ansible/roles/builder/build/tasks/create_sources.yml
tasks/tasks.py
tasks/vagrant.py

Also, fixing minor typo error.
Fixes: https://github.com/freeipa/freeipa-pr-ci/issues/20

[fix #20] Handling provision issues making it run twice.

---

build
run-pytest

build/run-pytest scripts: add timeout option

---

github/prci_github/internals.py

github: Use tasks file from target branch of PR

---

ansible/roles/runner/tasks/deploy_pr_ci.yml

runner: ensure prci is always started

---

README.md

README: document private keys permissions

---

README.md

README: update instruction for creating/uploading box

---

whitelist.yml

whitelist: add Tiboris

---

tasks/tasks.py

A hostname can be useful to identify which machine executed the job,
which can help to debug issues with a particular runner.

tasks: write hostname to file before job execution

---

ansible/roles/runner/handlers/main.yml
ansible/roles/runner/tasks/deploy_pr_ci.yml

runner: make sure prci is always enabled after deployment

---

scripts/prci_test_control.py

scripts: Control GitHub commit statuses from CLI

---

README.md
doc/README.md
doc/images/overview.svg
doc/images/phase-A.svg
doc/images/phase-B.svg
doc/images/phase-C.svg

doc: create developer documentation

---

whitelist.yml

whitelist: add frozencemetery

---

tasks/common.py

doc: explain purpose of execute_subtask()

---

whitelist.yml

please add me to the whitelist

whitelist: add new user

---

whitelist.yml

whitelist: add germanparente

---

README.md

There was missing backslash in README.md

Add missing backslash to README.md

---

github/prci_github/internals.py

!!!UNTESTED!!!
I don't have any PR CI deployment so this is untested.

github: Regenerate only failed tasks when RERUN_LABEL appears

---

README.md

Fixes: #107
A preview of it can be checked here: https://github.com/felipevolpone/freeipa-pr-ci/tree/doc-runner-reorder

Reordering development/production runner sections

---

scripts/prci_test_control.py

I rewrote prci_test_control to use docopt instead of argparse.

scripts: Docopt in prci_test_control

---

README.md
doc/README.md

Documentation from the POV of the developer and the user.
Fixes: #93

Adding documentation about re-running tasks

---

ansible/create_template_box.yml

Adding default values to create-template-box CLI

---

whitelist.yml

whitelist: add mrizwan93

---

ansible/cleanup_runner_disk.yml

Ansible script to remove vagrant boxes in hosts specified in runners inventory.
Fixes: #27

Script to cleanup vagrant boxes

---

whitelist.yml

whitelist: add ndehadrai

---

ansible/roles/machine/provision/tasks/main.yml

This should make it easier to search for a package in the listed packages.

Sort machine's packages

---

ansible/prepare_openclose_pr_tool.yml
ansible/roles/automation/openclose_pr/defaults/main.yml
ansible/roles/automation/openclose_pr/tasks/main.yml
ansible/roles/automation/openclose_pr/templates/config.yml
github/open_close_pr.py

This PR:
* Adds a new CLI tool to be able to open and close PRs. Below, it's described how to use it.
* Adds an ansible script to configure a PR CI runner to automatically use the tool above to create PRs (using crontab)
<details>
<summary>How to use the CLI tool</summary>
To open a PR:  
```
$ python3 github/open_close_pr.py --config config.yml open_pr
Running Open and Close PR Tool against felipevolpone/freeipa repo
Executing open_pr command
A new PR against felipevolpone/freeipa will be created with the title [Nightly Test PR] nt_20171128_104006
PR 55 created
$ python3 github/open_close_pr.py --config config.yml --prci_config ~/freeipa/.freeipa-pr-ci.yaml open_pr
```
To close a PR:  
```
$ python3 github/open_close_pr.py --config config.yml close_pr 55 --close_comment "Closing this PR" …
```

CLI tool to open and close PRs

---

ansible/prepare_openclose_pr_tool.yml
ansible/roles/automation/openclose_pr/tasks/main.yml
github/open_close_pr.py

* Adding the git package to be installed
* Disabling strict host checking for git clone
* Fixing how to parse a bool parameter in argparse
* Deleting local branch after creating the PR
* Changing how git clone is done
Fixes: #109

Improving and fixing issues in open_close CLI tool

---

doc/README.md
github/open_close_pr.py

Adding the docs of how to use openclose_pr.py script and how to deploy it. Also changing how the rebase is done before creating a new branch.

[openclose_pr tool] Improving docs, logs and how rebase is done

---

whitelist.yml

Signed-off-by: Pavel Picka <ppicka@redhat.com>

Add ppicka to whitelist

---

github/prci.py

As #188 was one-time temporary change it needs to be reverted.
Reverts freeipa/freeipa-pr-ci#188

Revert "[scalability] Fix behaviour to update stalled task"

---

github/internals/entities.py

Temporary commit, needs to be reverted later.

[temporary] Fix triggering abuse rate limits

---

tasks/common.py
tasks/vagrant.py

The cleanup patch which should fix the cleanup was apparently wrong.
This one removes pkill call and uses psutil module instead to do the
cleanup.

Kill Vagrant processes and VMs with psutil

---

whitelist.yml

Adding "menonsudhir" to whitelist.

Adding "menonsudhir" to whitelist

---

github/internals/entities.py

This patch fixes 8a2a771f4 where we were wrongly changing "world"
and thus second iteration of PR yielded instead of content of
symlink content of the yaml file and thus failing.

Fix editable PRCI nightly definition change

---

ansible/vars/fedora/28.yml
ansible/vars/ipa_branches/ipa-4-7.yml

Add missing f28 ansible var which was so far omitted.

add f28 ansible var

---

whitelist.yml

Signed-off-by: François Cami <fcami@redhat.com>

Add fcami to whitelist

---

.gitignore
autocleaner.py

autocleaner: fix taberror and add emacs gitignore entry

autocleaner: fix taberror and add emacs gitignore entry

---

whitelist.yml

Oleg Kozlov okozlov@redhat.com

Add xxblx to whitelist

---

ansible/roles/automation/openclose_pr/defaults/main.yml
ansible/roles/automation/openclose_pr/tasks/main.yml

This change allows to new nightlies being implemented as needed.
Signed-off-by: Diogo Nunes <dnunes@redhat.com>

Add new nightly dynamic

---

doc/prscheduler.md

The PR-CI scheduler tool has been improved with the ability to send PR to upgrade templates automatically. This PR updates the documentation accordingly.

devdocs: update documentation to cover template upgrade automation

---

ansible/roles/machine/provision/tasks/main.yml
ansible/roles/machine/provision/templates/hosts
ansible/roles/machine/provision/templates/ipa-test-config.yaml
templates/ad.vars.yml

This fixes the provisioning of hosts for all tests.

Fix tests that don't require AD

---

README.md
ansible/create_template_box.yml
ansible/hosts/runner_localhost
ansible/prepare_devel_test_runners.yml
ansible/prepare_openclose_pr_tool.yml
ansible/prepare_test_runners.yml
ansible/roles/machine/setup/defaults/main.yml
ansible/roles/machine/setup/tasks/install_packages.yml
ansible/vars/fedora/30.yml
ansible/vars/fedora/rawhide.yml
tasks/ansible.py
templates/ad.vars.yml
templates/run_pytest.vars.yml
vagrant/atlas.py
vagrant/box_uploader.py

Various fixes for rawhide / F30 PR-CI images.
* python2-dnf is no longer available, use Python 3 for Ansible
* Fix download URL for rawhide image
* ~Don't use Python dependency generator~
* Remove conflicting packages
* Fix box uploader
* Add Fedora 30 target
* Disable SELinux temporarily (due to https://github.com/freeipa/freeipa-pr-ci/pull/245#issuecomment-488171501)

Rawhide fixes

---

ansible/roles/windows/ipa-ad-data/tasks/main.yml

Required by new test case added by https://github.com/freeipa/freeipa/pull/3250

Add unixHomeDirectory to testuser

---

whitelist.yml

Whitelist: add miskopo

---

ansible/prepare_openclose_pr_tool.yml
ansible/roles/automation/nightly_pr/defaults/main.yml
ansible/roles/automation/setup/tasks/setup.yml
github/open_close_pr.py

Temporally disable template generation.
Replace Fedora 28 nightly with Fedora 29.

Fix PR Scheduler Tool

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Adding test never included in the dynamic declarations.

Add ipa-4-6 nightly execution

---

templates/vagrantfiles/Vagrantfile.master_1repl_1client
templates/vagrantfiles/Vagrantfile.master_2repl_1client
templates/vagrantfiles/Vagrantfile.master_3repl_1client

Issue: https://github.com/freeipa/freeipa-pr-ci/issues/288

Increase client0 memory

---

whitelist.yml

Stanislav contributes a lot of changes that are of good quality. Add him to the white list so that his pull requests trigger PR CI runs.

Add stanislavlevin to the white list

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Add job to test recently released branch https://github.com/freeipa/freeipa/tree/ipa-4-8.

Add nightly job for branch ipa-4-8

---

templates/vagrantfiles/Vagrantfile.master_2client

The new topology is needed for https://github.com/freeipa/freeipa/pull/3459

Add new vagrant template for topology with master and two clients

---

templates/vagrantfiles/Vagrantfile.master_2client

Fix typo in https://github.com/freeipa/freeipa-pr-ci/pull/298

Fix typo in parent's commit

---

ansible/provision_ad.yml
ansible/roles/machine/provision/templates/ipa-test-config.yaml
ansible/roles/windows/common/defaults/main.yml
ansible/roles/windows/common/tasks/main.yml
ansible/roles/windows/ipa-ad-data/tasks/main.yml
templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client

- Fix credentials used in latest version of peru's Windows image
- Add missing OpenSSH server to Windows
- Include ad_master_2client topology

Update Windows AD topologies

---

tasks/vagrant.py

Eventually PR-CI fails to bring Windows box up, returning `The device
is not ready`. A quick solution for that is to run that command once
again, wait a few moments and continue with the provisioning.
Issue: https://github.com/freeipa/freeipa-pr-ci/issues/307

Retry vagrant up if AD machine is not ready

---

whitelist.yml

David Sastre Medina should be in the whitelist.
Signed-off-by: François Cami <fcami@redhat.com>

Whitelist: add dawud

---

ansible/roles/windows/ad-root/tasks/certificate-authority.yaml
ansible/roles/windows/ad-root/tasks/main.yml
ansible/roles/windows/common/tasks/main.yml
templates/vagrantfiles/Vagrantfile.ad_master
templates/vagrantfiles/Vagrantfile.ad_master_2client

This PR is targeting execution of test_winsyncmigrate test suite but also improves stability for other AD-related tests.

Stabilize provisioning environments for AD-related tests

---

whitelist.yml

in order to be allowed to trigger PRCI tests

Add Gaurav to the whitelist

---

tasks/remote_storage.py

As of today more than 100,000 jobs were stored in dynamodb, generated page was huge and since wasn't possible to sort the results before fetching them this commit disables that.
PR-CI dashboard https://ci.freeipa.org/prs could be used to browse among the recent jobs and pull requests. 

Disable jobs root index generation

---

ansible/roles/windows/ipa-ad-data/tasks/main.yml

Added group 'group@group'
needed for PR: https://github.com/freeipa/freeipa/pull/4191

Add win_domain_group

---

ansible/vars/fedora/32.yml

Add Fedora 32 box image

---

autocleaner.py

https://github.com/freeipa/freeipa-pr-ci/issues/369
Signed-off-by: bbhavsar <bbhavsar@redhat.com>

Fix yaml safe_load with ruamel library

---

ansible/roles/windows/ad-root/tasks/main.yml
ansible/roles/windows/ad-subdomain/tasks/main.yml

This fixes https://pagure.io/freeipa/issue/8263

reset Administrator password after configuring AD

---

ansible/roles/windows/ad-subdomain/tasks/main.yml

Failures in: http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/79020510-baa0-11ea-8f85-fa163e19313f/runner.log.gz

Fix for indentation error.

---

ansible/provision_ad.yml
ansible/roles/windows/ad-root/tasks/main.yml
ansible/roles/windows/ad-subdomain/tasks/main.yml
ansible/roles/windows/common/tasks/main.yml

Failures observed in : http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/4a6b8d52-bac3-11ea-88b4-fa163e97fbb7/runner.log.gz

Change value for key of win_security_policy

---

ansible/vars/ipa_branches/ipa-4-9.yml

Add ipa-4-9 branch vars

---

github/internals/entities.py

By removing the sleep when locking a task the time between polling the
status and setting a new one is reduced, this is important to lower the
chances of a race condition.
"Taken" is being divided into "Locked" and "Taken", that can also help us
to troubleshoot future issues.
"pending for rerun" status now includes the runner that set it and when
it was set.

Make lock mechanism quicker and clearer

---

whitelist.yml

Allow antoniotorresm (Antonio Torres) to launch PRCI tests
Signed-off-by: Antonio Torres <antorres@redhat.com>

Allow antoniotorresm (Antonio Torres) to launch PRCI tests

---

ansible/roles/machine/provision/tasks/main.yml

force installation of freeipa packages from 'build' stage's repo

---

ansible/roles/machine/provision/tasks/main.yml

do not check gpg signature for test repo

---

ansible/roles/windows/sshd/defaults/main.yml
ansible/roles/windows/sshd/tasks/main.yml

Try several mirrors when installing cygwin

---

ansible/roles/automation/nightly_pr/defaults/main.yml

miskopo agreed to handle testing_master_previous run
from Thursdays.

Nightly tests: update reviewer for testing_master_previous

---

ansible/create_template_box.yml
ansible/roles/builder/prepare/templates/mock-fedora-branched.cfg.j2
ansible/roles/builder/prepare/templates/mock-fedora-rawhide.cfg.j2
ansible/roles/machine/setup/tasks/install_packages.yml
ansible/vars/fedora/35.yml
ansible/vars/fedora/rawhide.yml

* Fix Selenium and Geckodriver steps
* Selenium moved to Github releases
* Download latest geckodriver binary
* Issue: https://pagure.io/freeipa/issue/9029
* Add Fedora 35 vars and bump rawhide release version

Fix fedora 35 and rawhide images

---

ansible/roles/automation/nightly_pr/defaults/main.yml

Nightly definitions: change owners

---

whitelist.yml

in order to be allowed to trigger PRCI tests

Add Julien Rische to the whitelist

---

ansible/vars/fedora/36.yml
ansible/vars/fedora/rawhide.yml

Add Fedora 36 vars and bump rawhide release version

---

whitelist.yml

so that Iker is allowed to trigger PRCI tests

Add Iker Pedrosa to the whitelist

---

whitelist.yml

Allow droideck (Simon Pichugin) and dav-pascual (David Pascual)
to run freeipa PR-CI

Add contributors

---

whitelist.yml

Signed-off-by: Carla Martinez <carlmart@redhat.com>

Add carlmart to whitelist

---

whitelist.yml

Add mreynolds389 as allowed user to trigger PRCI tests

PRCI: add mreynolds389

---

whitelist.yml

Add mbhalodi to the list of contributors, to be
allowed to trigger gating tests on new PRs.

Contributors list: add Meha Bhalodiya

---

github/open_close_pr.py

Rarely the open_close_pr receives error from GitHub when opening a PR with message, e.g.:
"""
A pull request already exists for freeipa-pr-ci2:testing_master_latest """
The assumtion is that it might be caused by a race condition between deletion of branch of previous PR and GitHub not closing the previous PR fast enough.
This fix adds a delay before opening the MR to try to lower the probability of this race condition + it tries the opening up to 3 times.
The fix also moves out assignment of reviewer and deletion of local branch out of opening of PR to more clearly separate concerns of the individual methods.

fix: open_close_pr to re-try PR creation on error

---

ansible/vars/fedora/38.yml
ansible/vars/fedora/rawhide.yml

As a prep for creating new boxes for ipa-4-10 and master branches.

Add Fedora 38 vars and bump rawhide

---

whitelist.yml

Add Aleksandr Sharov as allowed user to trigger PRCI tests

PR-CI Whitelist: add kororland
